org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.114

mod_id=thaumaturgetweaks
mod_name=Thaumaturge Tweaks
mod_license=LGPL-3.0
mod_version=2.1.0
mod_group_id=com.blackmoss.thaumaturgetweaks
mod_authors=Black_Moss
mod_description=A quality-of-life addon mod for Thaumaturge.

## 26.1.2-NeoForge-1.0.2
thaumaturge_version=9095192
lithostitched_version=1.8.0-neoforge-26.1
architectury_version=20.1.16
cloth_config_version=26.1.154
rei_version=26.1.819
curios_version=15.0.0+26.1.2
jade_version=26.1.11+neoforge
trinkets_version=4.0.1+26.1
