org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76

mod_id=thaumaturgetweaks
mod_name=Thaumaturge Tweaks
mod_license=LGPL-3.0
mod_version=1.3.0
mod_group_id=com.blackmoss.thaumaturgetweaks
mod_authors=Black_Moss
mod_description=

rei_version=26.1.819
cloth_config_version=26.1.154
curios_version=15.0.0+26.1.2
jade_version=26.1.11+neoforge
